import { getDatabase, ref, onValue } from 'firebase/database';
import { LogEntry } from '../types/session';
import { InventoryItem } from '../types/inventoryItem';

/**
 * Activity analytics derived from the `log` node.
 *
 * Log messages are free text generated by utils/logging.ts, but they encode
 * quantity changes in a stable `OLD → NEW` form (e.g. "showroom: 5 → 10",
 * "qty 3 → 0", "container qty: 0 → 4") and the affected item as "Item #<code>".
 * We parse those two signals to reconstruct units flowing in and out without
 * needing a separate structured event store.
 */

export interface Movement {
  ts: number;
  userId: string;
  userName: string;
  /** Item code if the entry references one ("Item #ABC"), else null. */
  itemCode: string | null;
  /** Units added across all `X → Y` deltas in the message. */
  inUnits: number;
  /** Units removed across all `X → Y` deltas (positive number). */
  outUnits: number;
  /** inUnits - outUnits. */
  net: number;
  message: string;
}

export interface UserActivity {
  userId: string;
  userName: string;
  /** Number of log entries attributed to this user in the window. */
  actions: number;
  inUnits: number;
  outUnits: number;
  lastTs: number;
}

export interface ItemActivity {
  itemCode: string;
  name: string;
  type: string;
  /** Container category 0–4 (0 = none) from current inventory. */
  container: number;
  actions: number;
  inUnits: number;
  outUnits: number;
  net: number;
  lastTs: number;
}

export interface ActivityTotals {
  inUnits: number;
  outUnits: number;
  net: number;
  movements: number;
  activeItems: number;
  activeUsers: number;
}

const ITEM_CODE_RE = /Item #([^\s:)]+)/;
const CHANGE_RE = /(\d+)\s*→\s*(\d+)/g;

/** Parse a single log entry into a structured movement. */
export function parseMovement(log: LogEntry): Movement {
  const message = log.message || '';
  const codeMatch = ITEM_CODE_RE.exec(message);
  const itemCode = codeMatch ? codeMatch[1] : null;

  let inUnits = 0;
  let outUnits = 0;
  CHANGE_RE.lastIndex = 0;
  let m: RegExpExecArray | null;
  while ((m = CHANGE_RE.exec(message))) {
    const delta = Number(m[2]) - Number(m[1]);
    if (delta > 0) inUnits += delta;
    else if (delta < 0) outUnits += -delta;
  }

  return {
    ts: log.ts || 0,
    userId: log.userId || 'unknown',
    userName: log.userName || 'Unknown User',
    itemCode,
    inUnits,
    outUnits,
    net: inUnits - outUnits,
    message,
  };
}

/** Common windows for filtering activity by recency. */
export type RangeKey = '24h' | '7d' | '30d' | 'all';

export const RANGE_OPTIONS: { key: RangeKey; label: string; ms: number }[] = [
  { key: '24h', label: '24h', ms: 24 * 60 * 60 * 1000 },
  { key: '7d', label: '7 days', ms: 7 * 24 * 60 * 60 * 1000 },
  { key: '30d', label: '30 days', ms: 30 * 24 * 60 * 60 * 1000 },
  { key: 'all', label: 'All', ms: Infinity },
];

/** Keep only movements within `rangeMs` of `now`. */
export function withinRange(movements: Movement[], rangeMs: number, now: number): Movement[] {
  if (!isFinite(rangeMs)) return movements;
  const cutoff = now - rangeMs;
  return movements.filter((mv) => mv.ts >= cutoff);
}

/** Roll up movements into per-user activity, most recently active first. */
export function aggregateUsers(movements: Movement[], limit?: number): UserActivity[] {
  const map = new Map<string, UserActivity>();
  for (const mv of movements) {
    const key = mv.userId || mv.userName;
    const existing = map.get(key);
    if (existing) {
      existing.actions += 1;
      existing.inUnits += mv.inUnits;
      existing.outUnits += mv.outUnits;
      existing.lastTs = Math.max(existing.lastTs, mv.ts);
    } else {
      map.set(key, {
        userId: mv.userId,
        userName: mv.userName,
        actions: 1,
        inUnits: mv.inUnits,
        outUnits: mv.outUnits,
        lastTs: mv.ts,
      });
    }
  }
  const list = Array.from(map.values()).sort((a, b) => b.lastTs - a.lastTs);
  return limit ? list.slice(0, limit) : list;
}

/**
 * Roll up movements into per-item activity, joined against current inventory so
 * each item carries its name, type, and container category. Movements without a
 * resolvable item code are skipped.
 */
export function aggregateItems(
  movements: Movement[],
  itemsByCode: Map<string, InventoryItem>,
  limit?: number
): ItemActivity[] {
  const map = new Map<string, ItemActivity>();
  for (const mv of movements) {
    if (!mv.itemCode) continue;
    const inv = itemsByCode.get(mv.itemCode);
    const existing = map.get(mv.itemCode);
    if (existing) {
      existing.actions += 1;
      existing.inUnits += mv.inUnits;
      existing.outUnits += mv.outUnits;
      existing.net += mv.net;
      existing.lastTs = Math.max(existing.lastTs, mv.ts);
    } else {
      map.set(mv.itemCode, {
        itemCode: mv.itemCode,
        name: inv?.name || '(unknown item)',
        type: inv?.type || '',
        container: inv?.containers?.category || 0,
        actions: 1,
        inUnits: mv.inUnits,
        outUnits: mv.outUnits,
        net: mv.net,
        lastTs: mv.ts,
      });
    }
  }
  const list = Array.from(map.values()).sort(
    (a, b) => b.inUnits + b.outUnits - (a.inUnits + a.outUnits)
  );
  return limit ? list.slice(0, limit) : list;
}

/** Headline totals across a set of movements. */
export function totals(movements: Movement[]): ActivityTotals {
  let inUnits = 0;
  let outUnits = 0;
  const items = new Set<string>();
  const users = new Set<string>();
  for (const mv of movements) {
    inUnits += mv.inUnits;
    outUnits += mv.outUnits;
    if (mv.itemCode) items.add(mv.itemCode);
    users.add(mv.userId || mv.userName);
  }
  return {
    inUnits,
    outUnits,
    net: inUnits - outUnits,
    movements: movements.length,
    activeItems: items.size,
    activeUsers: users.size,
  };
}

/**
 * Subscribe to the activity log and receive parsed movements (newest first).
 * Returns an unsubscribe. `max` caps how many recent entries are processed.
 */
export function subscribeMovements(
  callback: (movements: Movement[]) => void,
  max = 1000
): () => void {
  const db = getDatabase();
  const logsRef = ref(db, 'log');
  return onValue(logsRef, (snapshot) => {
    const data = snapshot.val() || {};
    const logs: LogEntry[] = Object.entries(data)
      .filter(([, v]: [string, any]) => v && typeof v === 'object' && v.message)
      .map(([logId, v]: [string, any]) => ({
        logId,
        message: v.message || '',
        userId: v.userId || 'unknown',
        userName: v.userName || 'Unknown User',
        ts: v.ts || 0,
      }));
    logs.sort((a, b) => b.ts - a.ts);
    callback(logs.slice(0, max).map(parseMovement));
  });
}

/** Build a lookup of inventory items keyed by code. */
export function indexByCode(items: InventoryItem[]): Map<string, InventoryItem> {
  const map = new Map<string, InventoryItem>();
  for (const it of items) map.set(it.code, it);
  return map;
}
